In [1]:
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2=np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [9]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])

print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [14]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
## Universal Function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [16]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [18]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [19]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [21]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [23]:
### statistical concepts--Normalization(z-score normalization aka standardization)
##to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev

print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev=np.std(data)
print(std_dev)

variance=np.var(data)
print(variance)


5.5
5.5
2.8722813232690143
8.25


In [26]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])