# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [4]:
import numpy as np
import random
def get_random():
    random_number=random.randint(1,20)
    return random_number

lst=[]
for i in range(5):
    temp=[]
    for j in range(5):
        temp.append(get_random())
    lst.append(temp)
arr1=np.array(lst)
arr1

array([[ 9, 19, 12,  8,  3],
       [14, 19, 19, 15, 14],
       [14, 12, 19, 20, 18],
       [12, 18,  1, 14,  2],
       [ 5,  2, 19,  2, 12]])

In [6]:
arr1.shape

(5, 5)

In [7]:
arr1[0:,2]=1

In [8]:
arr1

array([[11, 18,  1,  3,  4],
       [16, 20,  1,  1,  4],
       [10, 17,  1, 11,  6],
       [ 3, 11,  1,  2, 17],
       [16,  6,  1, 12, 19]])

In [10]:

for i in range(5):
    arr1[i,i]=4

In [12]:
arr1

array([[ 4, 18,  1,  3,  4],
       [16,  4,  1,  1,  4],
       [10, 17,  4, 11,  6],
       [ 3, 11,  1,  4, 17],
       [16,  6,  1, 12,  4]])

In [13]:
arr1=np.random.randint(1,36,size=(6,6))

In [14]:
arr1

array([[17, 16, 12, 24, 19,  9],
       [ 8,  2, 12, 18,  1, 27],
       [21, 27, 33, 22, 22, 12],
       [29, 20, 34, 17, 19, 12],
       [12, 26, 22, 14, 11,  3],
       [ 2,  6, 26, 31,  9, 14]], dtype=int32)

In [16]:
arr1[2:5,1:4]

array([[27, 33, 22],
       [20, 34, 17],
       [26, 22, 14]], dtype=int32)

In [30]:
arr1=np.random.randint(1,21,size=(5,5))
arr1

array([[ 8, 10,  8, 12,  7],
       [ 2, 20,  1, 17, 20],
       [15,  1,  5,  9, 13],
       [ 3, 13,  5, 18,  6],
       [ 5, 12,  9,  9, 16]], dtype=int32)

In [45]:

border=np.concatenate((arr1[0,:],arr1[1:,-1],arr1[-1,-2::-1],arr1[-2:0:-1,0]))
border

array([ 8, 10,  8, 12,  7, 20, 13,  6, 16,  9,  9, 12,  5,  3, 15,  2],
      dtype=int32)

In [46]:
arr1=np.random.randint(1,12,size=(3,4))
arr2=np.random.randint(1,12,size=(3,4))

In [53]:
print(arr1)
arr2

[[ 3 10  7  2]
 [ 8  3  5 11]
 [ 3  6  1  8]]


array([[ 3,  7,  3,  3],
       [ 4, 11,  2,  3],
       [ 5, 11,  3,  7]], dtype=int32)

In [54]:
add=arr1+arr2
add

array([[ 6, 17, 10,  5],
       [12, 14,  7, 14],
       [ 8, 17,  4, 15]], dtype=int32)

In [55]:
arr1=np.random.randint(1,16,size=(4,4))
arr1

array([[ 1,  2, 15,  6],
       [ 1,  5,  9,  8],
       [ 9, 15, 12, 10],
       [ 3,  4, 15,  3]], dtype=int32)

In [59]:
col=np.sum(arr1,axis=0)
col

array([14, 26, 51, 27])

In [60]:
row=np.sum(arr1,axis=1)
row

array([24, 23, 46, 25])

In [62]:
arr=np.random.randint(1,25,size=(5,5))
arr

array([[12, 21,  6,  8, 10],
       [ 9, 20, 14, 14,  6],
       [18, 20, 21, 13, 20],
       [16, 23, 14,  5,  3],
       [20,  1, 23,  3,  5]], dtype=int32)

In [63]:
np.mean(arr)

np.float64(13.0)

In [64]:
np.median(arr)

np.float64(14.0)

In [67]:
np.std(arr)

np.float64(6.876045375068434)

In [69]:
np.var(arr)

np.float64(47.28)

In [70]:
(arr-np.mean(arr))/np.std(arr)

array([[-0.14543243,  1.16345945, -1.01802702, -0.72716216, -0.4362973 ],
       [-0.58172973,  1.01802702,  0.14543243,  0.14543243, -1.01802702],
       [ 0.72716216,  1.01802702,  1.16345945,  0.        ,  1.01802702],
       [ 0.4362973 ,  1.45432432,  0.14543243, -1.16345945, -1.45432432],
       [ 1.01802702, -1.74518918,  1.45432432, -1.45432432, -1.16345945]])

In [71]:
arr=np.random.randint(1,9,size=(3,3))
arr


array([[1, 3, 1],
       [2, 2, 2],
       [2, 8, 1]], dtype=int32)

In [72]:
arr1=np.random.randint(1,3,size=(3))

In [73]:
arr1

array([1, 1, 1], dtype=int32)

In [74]:
print(arr+arr1)

[[2 4 2]
 [3 3 3]
 [3 9 2]]


In [76]:
arr=np.random.randint(1,16,size=(4,4))
print(arr)
arr1=np.random.randint(1,4,size=(4))
arr1

[[ 9 11 13  9]
 [ 8 12 11  3]
 [ 1  6 15 13]
 [ 2  4 14  9]]


array([2, 2, 3, 1], dtype=int32)

In [77]:
print(arr-arr1[:,np.newaxis])

[[ 7  9 11  7]
 [ 6 10  9  1]
 [-2  3 12 10]
 [ 1  3 13  8]]


In [85]:
arr1=np.random.randint(1,3,size=(3,3))
np.linalg.det(arr1)

np.float64(-5.000000000000001)

In [86]:
np.linalg.inv(arr1)

array([[ 0.4,  0.4, -0.6],
       [ 0.4, -0.6,  0.4],
       [-0.6,  0.4,  0.4]])

In [87]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([ 5.,  1., -1.]), eigenvectors=array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
       [-5.77350269e-01,  2.69492349e-17, -8.16496581e-01],
       [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [90]:
arr1=np.random.randint(1,6,size=(2,3))
print(arr1)
arr2=np.random.randint(1,6,size=(2,3))
print(arr2)

[[4 1 5]
 [2 2 3]]
[[1 4 5]
 [4 2 4]]


In [92]:
np.multiply(arr1,arr2)

array([[ 4,  4, 25],
       [ 8,  4, 12]], dtype=int32)

In [93]:
arr=np.random.randint(1,9,size=(3,3))

In [94]:
arr

array([[2, 6, 1],
       [5, 7, 4],
       [7, 5, 4]], dtype=int32)

In [96]:
arr=arr.reshape(1,9)

In [97]:
arr.reshape(9,1)

array([[2],
       [6],
       [1],
       [5],
       [7],
       [4],
       [7],
       [5],
       [4]], dtype=int32)

In [5]:
arr=np.random.randint(1,25,size=(5,5))

In [8]:
arr=arr.flatten()

In [9]:
arr

array([ 9, 13, 12,  8, 16, 15, 17,  3,  9,  8,  7, 24,  1,  3,  1,  2,  6,
       22,  5,  3, 24, 13,  7, 18, 13], dtype=int32)

In [10]:
arr.reshape(5,5)

array([[ 9, 13, 12,  8, 16],
       [15, 17,  3,  9,  8],
       [ 7, 24,  1,  3,  1],
       [ 2,  6, 22,  5,  3],
       [24, 13,  7, 18, 13]], dtype=int32)

In [11]:
arr=np.random.randint(1,25,size=(5,5))
arr

array([[ 2, 19,  2,  7, 15],
       [24, 21,  6, 15, 13],
       [ 1,  1,  3,  3,  6],
       [ 5, 19,  5, 21, 12],
       [17, 13, 17, 13, 20]], dtype=int32)

In [12]:
arr[[0,0,-1,-1],[0,-1,-1,0]]

array([ 2, 15, 20, 17], dtype=int32)

In [14]:
arr=np.random.randint(1,16,size=(4,4))
arr[arr>10]=10

In [15]:
arr

array([[ 6,  6,  8, 10],
       [10,  3,  3,  8],
       [10,  9,  8,  2],
       [ 5,  9,  6,  3]], dtype=int32)

In [16]:
data_type=[("name","U10"),("age","i4"),("weight","f4")]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)
np.sort(data,order="age")

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]


array([('Charlie', 20, 65.2), ('Alice', 25, 55.5), ('Bob', 30, 85.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [18]:
data_type=[('x','i4'),('y','i4')]
data=np.array([(5,4),(2,3)],dtype=data_type)
print(data)

[(5, 4) (2, 3)]


In [21]:
np.sqrt((data['x'][:,np.newaxis]-data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)

array([[0.        , 3.16227766],
       [3.16227766, 0.        ]])

In [27]:
import numpy.ma as ma
data=np.random.randint(1,21,size=(4,4))
mask=data > 10
arr=ma.array(data,mask=mask)
print(arr)
arr.sum()

[[1 -- 6 --]
 [-- 1 -- 3]
 [-- 5 2 --]
 [9 7 6 --]]


np.int64(40)

In [36]:
data=np.random.randint(1,21,size=(3,3))
mask=np.eye(3,dtype=bool)
arr=ma.array(data,mask=mask)
print(arr)
mean=arr.mean()
arr.filled(mean)


[[-- 4 15]
 [20 -- 4]
 [17 11 --]]


array([[11,  4, 15],
       [20, 11,  4],
       [17, 11, 11]], dtype=int32)